<a href="https://colab.research.google.com/github/ArtDaryl/DSP/blob/main/DSP_Buenaventura.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
from numpy import sqrt
from fractions import Fraction

In [9]:
i =  1
H = (1 / np.sqrt(2)) * np.array([[1, 1], [1, -1]])
Y = np.array([[0,-i],[i,-0]])
O = np.array([[1,0],[1,1]])

In [11]:
#Det(H)
np.linalg.det(H)

-0.9999999999999999

In [13]:
#Det(Y)
np.linalg.det(Y)

1.0

In [18]:
#HY
H@Y

array([[ 0.70710678, -0.70710678],
       [-0.70710678, -0.70710678]])

In [19]:
#YH
Y@H

array([[-0.70710678,  0.70710678],
       [ 0.70710678,  0.70710678]])

In [20]:
#HH
H@H

array([[ 1.00000000e+00, -2.23711432e-17],
       [-2.23711432e-17,  1.00000000e+00]])

In [21]:
#YHO
Y@H@O

array([[0.        , 0.70710678],
       [1.41421356, 0.70710678]])

In [22]:
#HYO
H@Y@O

array([[ 0.        , -0.70710678],
       [-1.41421356, -0.70710678]])